baseurl = "https://www.luizpeixoto.com/"
theme           = "casper-two"
languageCode    = "pt-BR"
disqusShortname = ""

[pagination]
  pagerSize = 6

#SectionPagesMenu = "main"

[params]
  title       = "Luiz Peixoto"
  subtitle    = "Advocacia e Consultoria"

  cover       = "down/buildings.jpg"
  description = "Advocacia e Consultoria"
  metaDescription = "Luiz Peixoto Advocacia e Consultoria"
  customCSS = []
  RSSLink = ""

  twitterName = "@adv_luizpeixoto"
  fbName = "luizpeixoto.adv"
  githubName = "peixoto-ops"

  logo = ""
  orgName = "Luiz Peixoto"
  orgWebsite = "https://www.luizpeixoto.com"
  orgDescription = ""

  author = "Luiz Peixoto"
  authorAvatar = "down/Avatar.jpeg"
  authorLocation = "Rio de Janeiro, BR"
  authorWebsite = "https://github.com/peixoto-ops"
  authorDescription = "OABRJ 94719"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[permalinks]
  post = "/:slug/"

[[menu.main]]
  name = "Início"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Áreas de Atuação"
  url = "/areas/"
  weight = 180

[[menu.main]]
  name = "Primeiros Passos"
  url = "/tags/Iniciar/"
  weight = 170

[[menu.main]]
  name = "Ferramentas"
  url = "/ferramentas/"
  weight = 160

[[menu.main]]
  name = "Publicações"
  url = "/garden/"
  weight = 150

[[menu.main]]
  name = "Área do Cliente"
  url = "/area-cliente/"
  weight = 140

[[menu.main]]
  name = "Importante"
  url = "/categories/comunicação/"
  weight = 99

[[menu.main]]
  name = "Segurança"
  url = "/tags/segurança"
  weight = 95
